xlsynth/xlsynth-crate

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- build.rs
- src/c_api.rs
- tests/readme_test.rs
This add `rustc` cargo directives to link to `libxls` dso using regular C compiler flags (`-L` and `-l`) rather than relying on `libloading`.
This has the advantage of decoupling `c_api.rs` from the linkage type and can also allow static linking (and thus fixes #1) in bazel based environment.
This also patch the DSO using `install_name_tool` so that ld doesn't fail to link by trying to discover it from the bazel build path.
> build: link using rustc

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- build.rs
This release supports both x64 and arm64 dylibs on OS X.
> Bump release and restructure `build.rs`.

- Cargo.lock
- xlsynth-sys/Cargo.toml
- xlsynth/Cargo.toml
- xlsynth/src/vast.rs
- xlsynth/tests/vast_test.rs
This PR marks the structs and enums in `vast.rs` as `pub` to make them externally accessible, and adds tests of the external-facing API (`xlsynth/tests/vast_test.rs`). These tests are currently copies of tests in `xlsynth/src/vast.rs`.
Note: the instantiation test does not currently cover setting parameters values - I think that needs a mechanism for creating literal expressions, which I will implement in another PR.
> Make VAST API accessible and add API function for instantiation.

- Cargo.lock
- xlsynth-sys/Cargo.toml
- xlsynth/Cargo.toml
- xlsynth/src/ir_value.rs
- xlsynth/src/vast.rs
- xlsynth/tests/vast_test.rs
Provides a `make_literal` method for `VastFile` that accepts a literal value and format (both strings). The method returns an `Expr` that can be used in continuous assignments and for setting parameter values for module instances.
> Enable creation of literals

- Cargo.lock
- xlsynth-sys/Cargo.toml
- xlsynth-sys/build.rs
- xlsynth/Cargo.toml
- xlsynth/src/vast.rs
Skip download of the DSO when it's a docs.rs build, since that does not complete successfully.
Fix a few small issues seen in resulting doc build.
Tested via:
`$ DOCS_RS=1 cargo doc --no-deps`
> Try to fix docs.rs build

- xlsynth-sys/build.rs
- xlsynth-sys/src/lib.rs
- xlsynth/src/dslx.rs
- xlsynth/src/dslx_bridge.rs
- xlsynth/src/ir_value.rs
- xlsynth/src/lib.rs
Adds support for some new C APIs that help us reflect on struct definitions and their type information.
Also creates a typed wrapper around IrBits that imbues it with a constexpr signedness and bit count, which we use in struct definition generation.
Bumps DSO version required to v0.0.98.
> [dslx_bridge] Start generating struct definitions.

- sample-usage/build.rs
- xlsynth/src/dslx_bridge.rs
This decouples the target language from the DSLX struct so we can emit struct definitions for other bridging languages like SV.
> Introduce trait for building based on DSLX module contents.

- Cargo.lock
- README.md
- sample-usage/src/main.rs
- sample-usage/src/multithread.rs
- xlsynth-driver/Cargo.toml
- xlsynth-driver/src/main.rs
- xlsynth-driver/tests/invoke_test.rs
- xlsynth-sys/Cargo.toml
- xlsynth-sys/build.rs
- xlsynth-sys/src/lib.rs
- xlsynth/Cargo.toml
- xlsynth/src/ir_package.rs
- xlsynth/src/ir_value.rs
- xlsynth/src/lib.rs
- xlsynth/src/lib_support.rs
- xlsynth/src/vast.rs
Also factors out a bunch of non-public support code from lib.rs in the xlsynth package to lib_support.rs
This PR will initially fail but I'll re-run when the v0.0.120 DSO has finished releasing.
> [driver] Add ability to run dslx2pipeline via runtime APIs.

- Cargo.lock
- xlsynth-driver/Cargo.toml
- xlsynth-sys/Cargo.toml
- xlsynth/Cargo.toml
- xlsynth/src/ir_value.rs
- xlsynth/tests/function_zoo.x
- xlsynth/tests/ir_interpret_test.rs
This also adds a facility for cloning IR values -- it's not optimal but doing it this way doesn't need any change in the API to be simultaneously released.
> [xlsynth] Show arrays being passed to/from IR functions including multidimensional ones.

- .github/workflows/ci.yml
- .gitignore
- Cargo.lock
- Cargo.toml
- test-helpers/Cargo.toml
- test-helpers/tests/spdx_test.rs
- xlsynth-driver/Cargo.toml
- xlsynth-estimator/Cargo.toml
- xlsynth-estimator/build.rs
- xlsynth-estimator/proto/estimator_model.proto
- xlsynth-estimator/proto/sample_node.proto
- xlsynth-estimator/src/estimator.rs
- xlsynth-estimator/src/main.rs
This is a first step towards a pluggable delay estimator via the C API so environments can register new delay estimators.
Uses various case studies from the asap7 EstimatorModel protobuf.
> [xlsynth] Implement delay estimator in Rust

- xlsynth-sys/build.rs
- xlsynth-sys/src/lib.rs
- xlsynth/src/dslx.rs
- xlsynth/src/sv_bridge_builder.rs
- xlsynth/tests/structure_zoo.x
- xlsynth/tests/want_structure_zoo.golden.sv
Note: this should pass once the `v0.0.121` release of xlsynth is done: https://github.com/xlsynth/xlsynth/actions/runs/12383539921
> [sv_bridge] Fixes issue seen where type alias is not named same as original.

- Cargo.lock
- sample-usage/build.rs
- sample-usage/src/main.rs
- sample-usage/src/multithread.rs
- xlsynth-driver/Cargo.toml
- xlsynth-driver/src/ir2delayinfo.rs
- xlsynth-driver/src/main.rs
- xlsynth-driver/src/tools.rs
- xlsynth-driver/tests/invoke_test.rs
- xlsynth-estimator/Cargo.toml
- xlsynth-sys/Cargo.toml
- xlsynth-sys/build.rs
- xlsynth-sys/src/lib.rs
- xlsynth/Cargo.toml
- xlsynth/benches/bits_ops.rs
- xlsynth/benches/build_f32_tuple.rs
- xlsynth/benches/call_dslx.rs
- xlsynth/src/ir_package.rs
- xlsynth/src/ir_value.rs
- xlsynth/src/lib_support.rs
- xlsynth/src/rust_bridge_builder.rs
Adds a few benchmarks for calling IR for interpretation and packing / unpacking a float 3-tuple.
Also makes use of `expect()` with an associated message more consistently worded in the crate.
Fixes #101
> Add more value APIs to avoid stringy manipulation

- Cargo.lock
- xlsynth-driver/Cargo.toml
- xlsynth-estimator/Cargo.toml
- xlsynth-sys/Cargo.toml
- xlsynth/Cargo.toml
- xlsynth/src/ir_builder.rs
- xlsynth/src/lib_support.rs
Previous pattern used was:
```rust
let name_cstr = name.map(|s| CString::new(s).unwrap());
let name_ptr = if let Some(name_cstr) = name_cstr {
name_cstr.as_ptr()
} else {
std::ptr::null()
};
```
But that is _moving_ the cstring into the let binding and then we take a pointer to a thing that goes out of scope. We now use the as_ref to make sure we take a pointer without moving the owner:
```rust
let name_cstr = name.map(|s| CString::new(s).unwrap());
let name_ptr = name_cstr.as_ref().map_or(std::ptr::null(), |s| s.as_ptr());
```
> [xlsynth:ir_builder] Fix lifetime for CStrings.

- xlsynth/src/ir_builder.rs
- xlsynth/src/lib_support.rs
But the umul and smul operations cannot currently be distinguished because we only exposed the same-bit-width operations from the C API so far. When we add the ones that can produce an extended result we'll update these APIs.
> [xlsynth:ir_builder] Expose mul operations.

- .github/workflows/ci.yml
- .gitignore
- valgrind.supp
- xlsynth-g8r/fuzz/Cargo.lock
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_gatify.rs
- xlsynth-g8r/src/gate.rs
- xlsynth-g8r/src/get_summary_stats.rs
- xlsynth-g8r/src/ir2gate.rs
- xlsynth-g8r/src/xls_ir/ir.rs
- xlsynth-g8r/src/xls_ir/ir_parser.rs
- xlsynth-g8r/tests/gatify_tests.rs
Adds support for signed comparisons, umul/smul, shra (which was borked before).
Proves equivalence of the gate mappings for these ops vs XLS IR versions for bit counts up to 8 generally.
Multiplier gate mapping is a simple array multiplier with ripple carry adders for now.
Makes sure fuzzer can select among every op in the IR structure via a flat type we can more easily do `u.arbitrary<>` on.
> [g8r] Gatify everything needed for apfloat::mul

- Cargo.lock
- xlsynth-g8r/Cargo.toml
- xlsynth-g8r/benches/bf16_mul_gatesim_bench.rs
- xlsynth-g8r/src/test_utils.rs
- xlsynth-g8r/tests/gate_sim_vs_ir_interp.rs
- xlsynth/src/ir_value.rs
Non-scientific datapoint, for my M2 macbook running `cargo bench --bench bf16_mul_gatesim_bench` on battery gives:
```
bf16_mul_gatesim_zero_input/100
time:   [639.21 µs 642.12 µs 645.15 µs]
thrpt:  [155.00 Kelem/s 155.73 Kelem/s 156.44 Kelem/s]
change:
time:   [-6.4281% -5.8619% -5.3051%] (p = 0.00 < 0.05)
thrpt:  [+5.6023% +6.2269% +6.8697%]
Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
3 (3.00%) high mild
```
> [g8r] Add gatesim benchmark

- Cargo.lock
- xlsynth-g8r/Cargo.toml
- xlsynth-g8r/benches/bf16_mul_gatesim_bench.rs
- xlsynth-g8r/benches/gatify_bench.rs
- xlsynth-g8r/src/gate.rs
- xlsynth-g8r/src/ir2gate_utils.rs
- xlsynth-g8r/src/lib.rs
- xlsynth-g8r/src/propose_equiv.rs
- xlsynth-g8r/src/test_utils.rs
- xlsynth-g8r/src/validate_equiv.rs
- xlsynth-g8r/tests/gate_sim_vs_ir_interp.rs
- xlsynth-g8r/tests/gatify_tests.rs
Done via `varisat` due to its support for incremental clause addition and `assume`, super useful!
On my M2 macbook air on battery:
```
$ cargo test -p xlsynth-g8r --lib test_validate_equiv_bf16_mul --release -- --nocapture
Proposed 1036 equiv classes in 168.872917ms
Validated to 19 proven sets 46 counterexamples in 14.683458ms
test validate_equiv::tests::test_validate_equiv_bf16_mul ... ok
```
> [g8r] Add first cut of equivalence class validation.

- run_valgrind_on_tests.py
- xlsynth-driver/src/ir2gates.rs
- xlsynth-driver/src/main.rs
- xlsynth-g8r/src/fraig.rs
- xlsynth-g8r/src/gate.rs
- xlsynth-g8r/src/get_summary_stats.rs
- xlsynth-g8r/src/lib.rs
- xlsynth-g8r/src/main.rs
- xlsynth-g8r/src/process_ir_path.rs
- xlsynth-g8r/src/propose_equiv.rs
- xlsynth-g8r/src/validate_equiv.rs
- xlsynth-g8r/tests/gate_sim_vs_ir_interp.rs
- xlsynth/src/ir_value.rs
Basic components are:
- Propose probabilistic equivalence sets
- Prove them correct or not, if not then supply counterexamples for next probabilistic eval
- Iterate to convergence
Those were implemented in previous PRs -- basic idea comes from Alan Mishchenko's talks e.g. https://www.youtube.com/watch?v=dIEc_nPky7U -- the basic concept was intuitive enough I didn't need to read a paper but I understand that there are some.
With release build on Ryzen 9 7950X:
```
bf16_mul: live nodes: 1172 -> 1151 (1.79% improvement)
bf16_mul: depth: 109 -> 105 (3.67% improvement)
bf16_mul: took 474.967722ms
bf16_add: live nodes: 1303 -> 1167 (10.44% improvement)
bf16_add: depth: 130 -> 123 (5.38% improvement)
bf16_add: took 1.411344344s
```
> [g8r] Some form of "fraiging" implemented.

- Cargo.lock
- xlsynth-g8r/src/bulk_replace.rs
- xlsynth-g8r/src/check_equivalence.rs
- xlsynth-g8r/src/fraig.rs
- xlsynth-g8r/src/gate.rs
- xlsynth-g8r/src/gate2ir.rs
- xlsynth-g8r/src/ir2gate.rs
- xlsynth-g8r/src/propose_equiv.rs
- xlsynth-g8r/src/test_utils.rs
- xlsynth-g8r/src/validate_equiv.rs
This allows us to find gates that are inverse patterns of other gates and rewire them via a negated operand. Before we needed the polarities of gates to happen to match to find the substitution.
With release build on Ryzen 9 7950X:
```
bf16_mul: live nodes: 1172 -> 1147 (2.13% improvement)
bf16_mul: depth: 109 -> 105 (3.67% improvement)
bf16_mul: took 530.435484ms
bf16_add: live nodes: 1303 -> 1139 (12.59% improvement)
bf16_add: depth: 130 -> 120 (7.69% improvement)
bf16_add: took 2.402919234s
```
> [g8r] Also propose/verify *inverted* gate histories.

- xlsynth-g8r/src/fraig.rs
- xlsynth-g8r/src/fuzz_utils.rs
- xlsynth-g8r/src/propose_equiv.rs
- xlsynth-g8r/src/xls_ir/ir_node_env.rs
- xlsynth-g8r/src/xls_ir/ir_parser.rs
Plumbs context all around for better error message reporting.
Also make arbitrary bitstring generation work in a fallback slow way if it's more than 64 bits.
> [g8r] parser fix for identifiers starting with ret

- xlsynth-sys/Cargo.toml
Using rustls should be totally fine I believe since we don't care about performance here, and makes the build-dependencies easier to deal with.
> [build] Make build.rs pull the DSO via reqwest that does not take a dep on native SSL libraries

- xlsynth-driver/tests/invoke_test.rs
- use 4‑bit example in `test_ir2gates_determinism`
this improves the test runtime significantly
> Speed up determinism test

- xlsynth-g8r/src/main.rs
- remove redundant `default_value` attributes from clap argument definitions
> Fix clap arg duplication

- xlsynth-g8r/src/transforms/mod.rs
- xlsynth-g8r/src/transforms/swap_operands.rs
- add `swap_operands` transform for AND2 nodes
- expose new transform in module tree
- provide RNG wrapper and unit tests
- `cargo test -p xlsynth-g8r swap_operands -- --quiet`
> [g8r] Add swap_operands transform

- xlsynth-test-helpers/tests/version_test.rs
- skip version tests that require crates.io access if `CARGO_NET_OFFLINE` is set
- `cargo test -p xlsynth-test-helpers --test version_test -- --nocapture`
> guard network tests with offline env

- xlsynth-g8r/src/transforms/mod.rs
- xlsynth-g8r/src/transforms/toggle_output.rs
- implement new transform to toggle negation on an output bit
- expose RNG wrapper for picking a random output bit
- exercise new code with unit tests
- `cargo test -p xlsynth-g8r toggle_output_bit_self_inverse --quiet`
- `cargo test -p xlsynth-g8r toggle_output_bit_rand_round_trip --quiet`
- `cargo test -p xlsynth-g8r test_toggle_output_bit_invalid_indices --quiet`
> Add toggle_output transform

- xlsynth-g8r/src/transforms/mod.rs
- xlsynth-g8r/src/transforms/redundant_and.rs
- implement redundant AND transform and RNG wrappers
- wire transform into module list
- test round-trip insertion and removal and edge cases
- `cargo test`
> Add redundant AND transform

- .github/workflows/ci.yml
- xlsynth-g8r/fuzz/Cargo.lock
- xlsynth-g8r/fuzz/Cargo.toml
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_opt_equiv.rs
- xlsynth-g8r/src/check_equivalence.rs
- xlsynth-g8r/src/ir_equiv_boolector.rs
- xlsynth-g8r/src/transforms/toggle_output.rs
- xlsynth-test-helpers/src/ir_fuzz.rs
- create a new fuzz target checking optimized IR equivalence via Boolector
- include target in fuzz workspace
- run the target for 10s in CI
- `cargo fmt --all`
- `cargo check --workspace`
> Add IR optimization equivalence fuzz target

- .gitignore
- xlsynth/src/lib_support.rs
- ignore tool binaries and `slang`
- factor CString pointer creation into helper functions
- refactor call sites to use helpers
- `cargo check`
- `cargo test`
> Refactor CString utilities

- AGENTS.md
- xlsynth-g8r/src/transforms/mod.rs
- xlsynth-g8r/src/transforms/true_and.rs
- implement `true_and` transform that inserts an AND with constant true and collapses it
- expose new module in `transforms/mod.rs`
- add unit tests and RNG wrappers
- `cargo test -p xlsynth-g8r --quiet`
> [g8r] Add invertible true-and transform

- xlsynth-g8r/src/mcmc_logic.rs
- xlsynth-g8r/src/transforms/double_negate.rs
- xlsynth-g8r/src/transforms/duplicate.rs
- xlsynth-g8r/src/transforms/false_and.rs
- xlsynth-g8r/src/transforms/redundant_and.rs
- xlsynth-g8r/src/transforms/rotate_and.rs
- xlsynth-g8r/src/transforms/swap_operands.rs
- xlsynth-g8r/src/transforms/toggle_output.rs
- xlsynth-g8r/src/transforms/transform_trait.rs
- xlsynth-g8r/src/transforms/true_and.rs
- require `always_equivalent` to be implemented by each transform
- mark all transforms accordingly with `ToggleOutputBitTransform` returning `false`
- skip equivalence checks in MCMC when transforms are always equivalent
> [g8r] Optimize equivalence checking in MCMC

- xlsynth-g8r/src/transforms/mod.rs
- xlsynth-g8r/src/transforms/swap_outputs.rs
- xlsynth-g8r/src/transforms/transform_trait.rs
- implement SwapOutputBitsTransform for swapping output bits
- expose new transform via `TransformKind` and transform registry
- add tests for primitive and transform
- `cargo test --quiet`
> Add SwapOutputBits transform

- xlsynth-g8r/src/topo.rs
- xlsynth-g8r/src/transforms/mod.rs
- xlsynth-g8r/src/transforms/rewire_operand.rs
- xlsynth-g8r/src/transforms/rotate_and.rs
- xlsynth-g8r/src/transforms/transform_trait.rs
- implement `RewireOperandTransform` for reattaching a random AND operand
- expose the transform in the registry and add `TransformKind` variant
- include unit tests and formatting fixes
- `cargo test -p xlsynth-g8r --lib transforms::rewire_operand::tests::test_rewire_operand_transform_apply_forward_backward`
> [g8r] Add RewireOperand transform

- xlsynth-g8r/Cargo.toml
- xlsynth-g8r/src/bin/mcmc-driver.rs
- xlsynth-g8r/src/mcmc_logic.rs
- run multiple MCMC chains in parallel using all CPUs
- share best result across threads via new `Best` struct
- expose `Best` and hook into `mcmc` to update global best
- add `--threads` CLI flag to `mcmc-driver`
- add `num_cpus` crate for CPU count
> [g8r:mcmc] Add parallel multi-threaded MCMC driver

- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_opt_equiv.rs
- xlsynth-g8r/src/validate_equiv.rs
- xlsynth-g8r/tests/test_gate_equiv_varisat.rs
- move SAT-based gate equivalence into existing validate_equiv module
- reuse add_tseitsin* helpers to avoid duplication
- wire new API into fuzzing harness and tests
- `cargo test --test test_gate_equiv_varisat`
> [g8r] Implement SAT-based GateFn equivalence

- xlsynth-g8r/src/transforms/mod.rs
- xlsynth-g8r/src/transforms/split_fanout.rs
- xlsynth-g8r/src/transforms/transform_trait.rs
- add SplitFanout and MergeFanout transforms to duplicate an AND gate and rewire a specific fanout edge
- allow merges of these duplicates when fanouts reconverge
- expose the new transforms via `get_all_transforms`
- extend `TransformKind` and `TransformLocation` enums
- include unit tests for the new behaviour
- `cargo test`
> Add fan-out splitting transform

- xlsynth-g8r/src/bin/mcmc-driver.rs
- xlsynth-g8r/src/mcmc_logic.rs
- allow mcmc-driver to accept `.g8r` gate function text
- detect `.g8r` vs `.ir` in `load_start`
- mention `.g8r` in CLI help text
> Improve MCMC driver input handling

- .github/workflows/ci.yml
- AGENTS.md
- xlsynth-g8r/fuzz/Cargo.toml
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_gate_fn_roundtrip.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_gate_transform_equiv.rs
- xlsynth-g8r/fuzz/src/lib.rs
- xlsynth-g8r/src/transforms/mod.rs
- refactor GateFn fuzz graph generation into a small library crate
- expose `get_equiv_transforms` for transforms that are always equivalent
- add a new fuzz target `fuzz_gate_transform_equiv`
- use the library in `fuzz_gate_fn_roundtrip`
- run the new fuzzer and `fuzz_gate_fn_roundtrip` in CI
> Add fuzz transform equivalence test

- xlsynth-g8r/src/mcmc_logic.rs
- xlsynth-g8r/src/test_utils.rs
- xlsynth-g8r/tests/invoke_mcmc_driver_test.rs
- add helper in test_utils to build an 8-bit ripple-carry adder
- recognize `samples://ripple_carry_adder_8b` in the MCMC driver
- test invoking mcmc-driver with the new sample
- `cargo test --test invoke_mcmc_driver_test -- --nocapture`
- `cargo test --quiet`
> Add ripple carry adder sample and mcmc driver test

- xlsynth-driver/src/ir_equiv.rs
- xlsynth-g8r/benches/mcmc_benchmark.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_gate_transform_equiv.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_opt_equiv.rs
- xlsynth-g8r/src/bin/check-ir-equivalence.rs
- xlsynth-g8r/src/fraig.rs
- xlsynth-g8r/src/ir_equiv_boolector.rs
- xlsynth-g8r/src/mcmc_logic.rs
- xlsynth-g8r/src/propose_equiv.rs
- xlsynth-g8r/src/validate_equiv.rs
- xlsynth-g8r/tests/test_gate_equiv_varisat.rs
Also remove gate equivalence from the IR fuzzing test, we should do a dedicated one for g8r opt fuzzing and subsequent equivalence.
> [g8r] Rename proof routines for clarity.

- xlsynth-g8r/src/lib.rs
- xlsynth-g8r/src/match_and_rewrite.rs
- implement basic AST for AIG pattern matching and rewriting
- provide parser for expressions like `~AND(a, b) => AND(~a, ~b)`
- expose the module from `xlsynth-g8r`
- add unit tests
- `cargo test -p xlsynth-g8r --tests`
> [g8r] Add simple AIG pattern matcher parser

- xlsynth-driver/README.md
- xlsynth-driver/src/dslx2ir.rs
- xlsynth-driver/src/dslx2pipeline.rs
- xlsynth-driver/src/dslx_g8r_stats.rs
- xlsynth-driver/src/main.rs
- xlsynth-driver/src/tools.rs
- xlsynth-driver/tests/invoke_test.rs
- xlsynth-g8r/src/bin/mcmc-driver.rs
- xlsynth-sys/build.rs
The main benefit of this flag is that it enables an attempt at migrating .x files with no associated source text changes (e.g. that would change the position metadata in the resulting IR file)
This flag may be short lived as it will likely be the default mode when TIv1 is deleted, but it may assist with migration testing.
> [driver] Add type_inference_v2 flags to dslx2... subcommands

- xlsynth/src/lib_support.rs
`c_strs_to_rust` should free the pointer array.
> Free memory in `c_strs_to_rust`

- xlsynth-sys/build.rs
- xlsynth-sys/src/lib.rs
It is subtly wrong to use the Rust global xlsynth_sys::XLS_DSO_PATH from a
build.rs.  Instead you should read the new envvar DEP_XLSYNTH_DSO_PATH.
See explanation in the commit itself.
> Expose a DSO_PATH that works properly from build.rs under cross-compilation.

- xlsynth-driver/src/ir_equiv.rs
- xlsynth-driver/src/ir_equiv_batch.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_opt_equiv.rs
- xlsynth-g8r/src/bin/check-ir-equivalence.rs
- xlsynth-g8r/src/ir_equiv_boolector.rs
This PR extends the Boolector-based IR equivalence checker to also report the actual outputs for counterexamples, improving debugging:
- Records both inputs and outputs in the counterexamples.
- Updates CLI and driver to print outputs.
- Adjusts parallel/bit-split prover and fuzz targets for the new counterexample representation.
Note that in this version, the outputs are reported flatten.
> Report outputs in counterexamples

- .github/workflows/ci.yml
- .gitignore
- xlsynth-g8r/Cargo.toml
- xlsynth-g8r/src/equiv/easy_smt_backend.rs
- xlsynth-g8r/src/equiv/mod.rs
- xlsynth-g8r/src/equiv/solver_interface.rs
- xlsynth-g8r/src/lib.rs
This pull request adds a generic solver interface that could be used to abstract solvers accessed by both binary or FFI.
Binary interface through easy_smt is also added.
commit-id:6684c5bd
---
**Stack**:
- #420
- #419
- #415
- #413
- #412
- #411
- #410
- #409
- #408
- #407
- #406
- #405
- #404
- #403 ⬅
> Add generic solver interface, add easy_smt backend

- xlsynth-driver/tests/invoke_test.rs
- xlsynth-g8r/src/dslx_stitch_pipeline.rs
- xlsynth-sys/build.rs
- xlsynth-sys/src/lib.rs
- xlsynth/src/dslx.rs
- xlsynth/src/dslx_bridge.rs
We wanted the stitch command to check that the `_cycle\d+` suffixed functions are concrete and not parametric.
> Bump DSO to v0.0.212, introduce parametric query API, use in stitch command

- xlsynth-g8r/src/equiv/bitwuzla_backend.rs
- xlsynth-g8r/src/equiv/boolector_backend.rs
- xlsynth-g8r/src/equiv/easy_smt_backend.rs
- xlsynth-g8r/src/equiv/prove_equiv.rs
- xlsynth-g8r/src/equiv/solver_interface.rs
- xlsynth-sys/src/lib.rs
- xlsynth/src/ir_value.rs
- xlsynth/src/lib_support.rs
Boolector is using true/false as their one-bit bitvector value, which isn't parsed correctly before. This pull request fixes it.
commit-id:01ed342e
---
**Stack**:
- #451
- #450
- #449
- #446
- #445
- #444
- #443 ⬅
> Fix parsing of boolector get-value results

- .github/workflows/publish.yml
This is needed after introducing the tests for quickchecks.
> Fix the publish script to download the prove_quickcheck_main binary

- xlsynth-driver/src/ir_equiv.rs
- xlsynth-driver/src/main.rs
- xlsynth-driver/src/prove_quickcheck.rs
- xlsynth-g8r/src/equiv/prove_equiv.rs
- xlsynth-g8r/src/equiv/prove_quickcheck.rs
In the future, we should probably change all such flags to use . This pull request only do this for assertion semantics
> Add help messages for assertion semantics

- xlsynth-driver/src/common.rs
- xlsynth-driver/src/main.rs
- xlsynth-driver/src/run_verilog_pipeline.rs
- xlsynth-driver/tests/invoke_test.rs
Fix run-verilog-pipeline argument order and add zero-value defaults
Improves the UX of the run-verilog-pipeline subcommand by:
- Swap argument order: SystemVerilog path is now first (required), input value is second (optional)
- Auto zero-values: When no input value provided, automatically generates appropriate zero values based on detected port widths
- Better UX messaging: Shows what input values are being used and provides copy-paste command for next run
- Fix slang invocation: Restore correct slang flags (--single-unit --quiet --ast-json -) with detailed comments explaining each flag's purpose
- Enhanced error handling: Add comprehensive debug logging and clearer error messages
- Update tests: Fix test argument order to match new API
Before: xlsynth-driver run-verilog-pipeline …
> [driver] UI fixes for run-verilog-pipeline subcommand.

- xlsynth-driver/src/ir_equiv.rs
- xlsynth-driver/src/prove_quickcheck.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_opt_equiv.rs
- xlsynth-g8r/src/bin/check-ir-equivalence.rs
- xlsynth-g8r/src/equiv/prove_equiv.rs
- xlsynth-g8r/src/equiv/prove_quickcheck.rs
Fix print order for the function input in proof results (fixes #456). Always print the value no matter assertion happens or not (fixes #457).
> Fix result printing bugs

- xlsynth-driver/src/dslx_equiv.rs
- xlsynth-driver/src/ir_equiv.rs
- xlsynth-driver/src/main.rs
- xlsynth-driver/src/parallelism.rs
- xlsynth-driver/tests/invoke_test.rs
This pull request adds a dslx-equiv command that combines the translation from DSLX to IR and proving of IR equivalence into one command.
> Add convenient dslx-equiv command

- xlsynth-driver/src/prove_quickcheck.rs
- xlsynth-driver/tests/invoke_test.rs
- xlsynth/src/lib.rs
Make prove-quickcheck more robust by falling back to itok mangled vesions when the wrapper isn't available
In the original XLS system, it seems that each quickcheck function will be individually translated by converting to an individual module with this function as the entry point. This will trigger the system to generate a wrapper (likely by `WrapEntryIfImplicitToken`) that fixes the activation bit to 1.
In our implementation, we do not convert into single function package. Then, our quickcheck functions may not get the wrapper functions. Thus, the lookup of the ordinary function name will fail.
The fix now lookup both the ones with or without implicit token and use our mechanism of fixing such bits.
> Make prove-quickcheck more robust

- xlsynth-driver/src/run_verilog_pipeline.rs
- xlsynth-driver/tests/invoke_test.rs
Adds tests for all non-combinational specifications, e.g.
- input_flops=false|true combined with output_flops=false|true
- when both input_flops=false and output_flops=false we need pipeline_stages=2 so we have a non-combinational circuit to test
> [driver] Correct support for run-verilog-pipeline when input/output valid signaling is provided

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- xlsynth-driver/src/common.rs
- xlsynth-driver/src/dslx_stitch_pipeline.rs
- xlsynth-driver/src/flag_defaults.rs
- xlsynth-driver/src/main.rs
- xlsynth-driver/src/toolchain_config.rs
- xlsynth-driver/tests/invoke_test.rs
- xlsynth-driver/tests/test_dslx2pipeline_array_index_bounds_checking_enum_cast_false.golden.sv
- xlsynth-driver/tests/test_dslx2pipeline_array_index_bounds_checking_enum_cast_true.golden.sv
- xlsynth-driver/tests/test_dslx_stitch_pipeline_array_index_bounds_checking_enum_cast_false.golden.sv
- xlsynth-driver/tests/test_dslx_stitch_pipeline_array_index_bounds_checking_enum_cast_true.golden.sv
- xlsynth-g8r/src/dslx_stitch_pipeline/common.rs
- xlsynth-g8r/src/dslx_stitch_pipeline/mod.rs
- xlsynth-sys/build.rs
The option can now be set in the toolchain config toml
We also add checking that our default arguments are the same as those seen in the underlying tool(s) -- but right now we just test vs codegen_main, the facility should be reusable
> Add a test case that shows invariant assertions being added/elided via codegen option

- xlsynth-driver/Cargo.toml
- xlsynth-driver/src/main.rs
- xlsynth-driver/src/prover.rs
- xlsynth-driver/tests/invoke_test.rs
This pull request adds a parallel scheduler for the proofs.
Tasks can be organized in a tree where each group of tasks may have the `all`, `any`, or `first` semantics.
For the `all` semantics, all the subtrees must be successful to make the overall task successful. A single failure will cause the scheduler to shutdown all the tasks in the group and report.
For the `any` semantics, any success in the subtrees could lead to overall task success. A single success will cause the scheduler to shutdown all the tasks in the group.
For the `first` semantics, the group's result is determined by the first finished task. All other tasks will be canceled after this.
The reason why we have a tree structure is that if we want to introduce a tactic/proof strategy/decomposition system, the proof …
> Add parallel scheduler

- xlsynth-g8r/src/equiv/bitwuzla_backend.rs
- xlsynth-g8r/src/equiv/boolector_backend.rs
- xlsynth-g8r/src/equiv/easy_smt_backend.rs
- xlsynth-g8r/src/equiv/solver_interface.rs
> Add declare_fresh

- xlsynth-g8r/Cargo.toml
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_gate_transform_arbitrary.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_gatify.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_opt_equiv.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_roundtrip.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_same_sig_pair.rs
- xlsynth-g8r/src/xls_ir/ir_fuzz.rs
- xlsynth-g8r/src/xls_ir/mod.rs
- xlsynth-test-helpers/src/lib.rs
Fixes bug where we could not create slicing with bit counts necessary, underlying storage is now u64 for the bit counts for the fuzz ops.
> Move ir_fuzz library to xls_ir folder and fix bug

- FUZZ.md
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_outline_equiv.rs
- xlsynth-g8r/src/xls_ir/ir_outline.rs
This will be useful for lining up parameters and return values to unify a function signature across dual outlined graphs.
> Add outline parameter/return spec.

- xlsynth-g8r/fuzz/fuzz_targets/fuzz_gatify.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_eval_interp_equiv.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_opt_equiv.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_outline_equiv.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_rebase_equiv.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_roundtrip.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_same_sig_pair.rs
- xlsynth-pir/src/ir_fuzz.rs
Enhancements:
* Multiple parameters are supported.
* Limits are placed on the total number of elements (recursive) in an array/tuple. Previously, the number could be exponentially large resulting in exponentially large graphs when generating pairs of functions with the same signature because the second matching function is concievably built element-by-element.
* Types are tracked more precisely with FuzzOps. This is required to count the number of elements in an array/tuple.
> Various enhancements to ir_fuzz.rs.

- README.md
- download_release.py
- get_required_xls_release_tag.py
- xlsynth-driver/README.md
- xlsynth-driver/src/greedy_eco.rs
- xlsynth-driver/src/main.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_gatify.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_eval_interp_equiv.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_opt_equiv.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_outline_equiv.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_rebase_equiv.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_roundtrip.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_same_sig_pair.rs
- xlsynth-pir/fuzz/Cargo.toml
- xlsynth-pir/fuzz/FUZZ.md
- xlsynth-pir/fuzz/fuzz_targets/fuzz_greedy_matching_ged.rs
- xlsynth-pir/fuzz/fuzz_targets/fuzz_naive_matching_ged.rs
- xlsynth-pir/fuzz/src/equiv.rs
- xlsynth-pir/fuzz/src/lib.rs
- xlsynth-pir/src/dce.rs
- xlsynth-pir/src/greedy_matching_ged.rs
- xlsynth-pir/src/ir_fuzz.rs
- xlsynth-pir/src/lib.rs
- xlsynth-pir/src/matching_ged.rs
- xlsynth-pir/src/node_hashing.rs
- xlsynth-sys/build.rs
The algorithm greedily matches node pairs in the old and new IR graphs based on a priority scheme. Add-node and delete-node edit actions are enqueued if no good matches exist.
ECO can be run like so:
xlsynth-driver greedy-eco old.opt.ir new.opt.ir \
--old_ir_top=main --new_ir_top=main \
--patched_out=patched.opt.ir \
--edits_debug_out=edits.txt
> Add a greedy ECO computation algorithm.
