xlsynth/xlsynth-crate

- Cargo.lock
- xlsynth-driver/Cargo.toml
- xlsynth-sys/Cargo.toml
- xlsynth/Cargo.toml
- xlsynth/src/dslx.rs
> Hold on to CString values for duration of import data creation call.

- Cargo.lock
- xlsynth-driver/Cargo.toml
- xlsynth-driver/src/main.rs
- xlsynth-driver/tests/invoke_test.rs
- xlsynth-sys/Cargo.toml
- xlsynth/Cargo.toml
- xlsynth/src/ir_value.rs
- xlsynth/src/lib.rs
> Getting driver to use a toolchain toml file.

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- README.md
Also add some notes in the README for the dev flow.
> Try to run the same pre-commit process in CI.

- xlsynth-driver/src/main.rs
- xlsynth-sys/build.rs
- xlsynth-sys/src/lib.rs
- xlsynth/src/dslx.rs
- xlsynth/src/dslx_bridge.rs
- xlsynth/src/rust_bridge_builder.rs
- xlsynth/src/sv_bridge_builder.rs
Bumps xlsynth dependency version.
Also fixes #45
> Have bridge handle alias definitions (Rust & SV).

- Cargo.lock
- xlsynth-driver/Cargo.toml
- xlsynth-driver/src/main.rs
- xlsynth-sys/Cargo.toml
- xlsynth/Cargo.toml
and bool flags with similar behavior to gflags booleans
> Some more uniform handling of codegen flags

- .github/workflows/ci.yml
- Cargo.lock
- test-helpers/Cargo.toml
- test-helpers/src/assert_valid_sv.rs
- test-helpers/src/lib.rs
- xlsynth-driver/Cargo.toml
- xlsynth-driver/tests/invoke_test.rs
- xlsynth-sys/Cargo.toml
- xlsynth/Cargo.toml
- xlsynth/src/sv_bridge_builder.rs
- xlsynth/tests/sv_bridge_test.rs
CI for slang on linux systems.
> Validate SV output via slang in tests.

- Cargo.lock
- xlsynth-driver/Cargo.toml
- xlsynth-driver/src/main.rs
- xlsynth-estimator/Cargo.toml
- xlsynth-sys/Cargo.toml
- xlsynth/Cargo.toml
mechanical port to clap 4.5.+: I just checked that it compiles and that the tests run but I'm sure there is cleaner (and more rust-ful) way to express this w/ the updated version.
> xlsynth-driver: bump to clap 4.5

- .github/workflows/ci.yml
- Cargo.lock
- xlsynth-driver/Cargo.toml
- xlsynth-estimator/Cargo.toml
- xlsynth-sys/Cargo.toml
- xlsynth-sys/build.rs
- xlsynth/Cargo.toml
Not sure why curl is giving failed downloads but I presume good error Results should help
> Ditch curl in build.rs for reqwest

- .github/workflows/ci.yml
- Cargo.lock
- download_release.py
- test-helpers/tests/spdx_test.rs
- xlsynth-driver/Cargo.toml
- xlsynth-driver/src/main.rs
- xlsynth-driver/tests/invoke_test.rs
- xlsynth-sys/build.rs
Adds tool downloader script we can use in CI.
> Dual-path all driver tests to try runtime APIs and tools, bump DSO so enabling warnings works for `ir_converter_main`

- Cargo.lock
- README.md
- xlsynth-driver/Cargo.toml
- xlsynth-estimator/Cargo.toml
- xlsynth-sys/Cargo.toml
- xlsynth-sys/build.rs
- xlsynth-sys/src/lib.rs
- xlsynth/Cargo.toml
- xlsynth/benches/f32_add.rs
- xlsynth/src/ir_package.rs
- xlsynth/src/lib.rs
- xlsynth/src/lib_support.rs
From cargo bench:
```
f32_add_nojit           time:   [4.9360 ms 5.0443 ms 5.1555 ms]                          
f32_add_jit             time:   [1.9670 µs 1.9928 µs 2.0250 µs]                         
```
> Add function JIT and API sample using it.

- sample-usage/src/main.rs
- xlsynth-sys/build.rs
- xlsynth-sys/src/lib.rs
- xlsynth/src/ir_builder.rs
- xlsynth/src/ir_package.rs
- xlsynth/src/lib.rs
- xlsynth/src/lib_support.rs
Requires APIs released in v0.0.167 DSO
> [xlsynth] Add XLS IR builder APIs to crate.

- Cargo.lock
- xlsynth-driver/Cargo.toml
- xlsynth-estimator/Cargo.toml
- xlsynth-sys/Cargo.toml
- xlsynth/Cargo.toml
- xlsynth/src/ir_builder.rs
- xlsynth/src/lib_support.rs
...or they can drop on return from frame.
> [xlsynth:ir_builder] Wrap droppables immediately

- xlsynth-g8r/src/lib.rs
- xlsynth-g8r/src/liberty/liberty_parser.rs
- xlsynth-g8r/src/liberty/mod.rs
Reads in the generic block/attribute grammar, doesn't look for any particular format within that yet.
> [g8r] Start of liberty format loader.

- Cargo.lock
- xlsynth-g8r/Cargo.toml
- xlsynth-g8r/src/lib.rs
- xlsynth-g8r/src/liberty/ascii_stream.rs
- xlsynth-g8r/src/liberty/liberty_parser.rs
- xlsynth-g8r/src/liberty/mod.rs
- xlsynth-g8r/src/liberty/try_parse.rs
e.g. scientific notation parsing, lineno/colno positions, binary to run
> [g8r] Liberty parser char streaming and a few more features

- Cargo.lock
- xlsynth-driver/Cargo.toml
- xlsynth-estimator/Cargo.toml
- xlsynth-g8r/Cargo.toml
- xlsynth-g8r/fuzz/Cargo.toml
- xlsynth-g8r/src/ir2gate.rs
- xlsynth-g8r/src/process_ir_path.rs
- xlsynth-g8r/src/xls_ir/ir.rs
- xlsynth-g8r/src/xls_ir/ir_parser.rs
- xlsynth-g8r/src/xls_ir/ir_utils.rs
- xlsynth-g8r/tests/gatify_tests.rs
- xlsynth-sys/Cargo.toml
- xlsynth/Cargo.toml
Does a one_hot_select without the default value.
> [g8r] Add support for array index that is assumed in bounds.

- Cargo.lock
- xlsynth-driver/Cargo.toml
- xlsynth-driver/README.md
- xlsynth-driver/src/ir_equiv.rs
- xlsynth-driver/src/main.rs
- xlsynth-driver/src/report_cli_error.rs
- xlsynth-driver/tests/invoke_test.rs
- xlsynth-estimator/Cargo.toml
- xlsynth-g8r/Cargo.toml
- xlsynth-g8r/fuzz/Cargo.toml
- xlsynth-sys/Cargo.toml
- xlsynth/Cargo.toml
Also consolidate some error reporting code and make the formatting nicer when toml file is not found.
> [driver] Make sure ir-equiv command gives back error retcode.

- xlsynth-g8r/fuzz/fuzz_targets/fuzz_gatify.rs
- xlsynth-g8r/src/ir2gate.rs
- xlsynth-g8r/tests/gatify_tests.rs
Supplements #173 with tests (so supercedes it) thanks @cchan for the array impl
> Add array op tests.

- .github/workflows/ci.yml
- Cargo.lock
- xlsynth-driver/src/ir2gates.rs
- xlsynth-driver/src/main.rs
- xlsynth-g8r/Cargo.toml
- xlsynth-g8r/benches/gatify_bench.rs
- xlsynth-g8r/fuzz/Cargo.lock
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_gatify.rs
- xlsynth-g8r/src/aig_hasher.rs
- xlsynth-g8r/src/aig_simplify.rs
- xlsynth-g8r/src/check_equivalence.rs
- xlsynth-g8r/src/emit_netlist.rs
- xlsynth-g8r/src/find_structures.rs
- xlsynth-g8r/src/gate.rs
- xlsynth-g8r/src/gate2ir.rs
- xlsynth-g8r/src/gate_builder.rs
- xlsynth-g8r/src/gate_sim.rs
- xlsynth-g8r/src/ir2gate.rs
- xlsynth-g8r/src/ir2gate_utils.rs
- xlsynth-g8r/src/lib.rs
- xlsynth-g8r/src/main.rs
- xlsynth-g8r/src/process_ir_path.rs
- xlsynth-g8r/src/test_utils.rs
- xlsynth-g8r/tests/gate_sim_vs_ir_interp.rs
- xlsynth-g8r/tests/gatify_tests.rs
- xlsynth-g8r/tests/test_adder_equivalence.rs
Expecting this first cut sets the stage for more advanced hash-based dedupe.
Also noticed that folding was disabled by default with the xlsynth-driver entry point so flipped that to default to true.
Also migrates us off ubuntu-2004 runner that is being sunsetted.
> [g8r] Single-level hash blake3 for content addressing.

- Cargo.lock
- xlsynth-g8r/Cargo.toml
- xlsynth-g8r/benches/bf16_mul_gatesim_bench.rs
- xlsynth-g8r/src/gate.rs
- xlsynth-g8r/src/gate_sim.rs
- xlsynth-g8r/src/lib.rs
- xlsynth-g8r/src/propose_equiv.rs
- xlsynth-g8r/src/test_utils.rs
- xlsynth-g8r/tests/gate_sim_vs_ir_interp.rs
Another step towards "fraiging" like solution where concrete simulation suggests clauses to unify or un-unify.
> [g8r] Propose equivalence class candidates based on concrete simulation.

- Cargo.lock
- xlsynth-driver/src/ir2gates.rs
- xlsynth-driver/src/main.rs
- xlsynth-driver/tests/invoke_test.rs
- xlsynth-g8r/src/count_toggles.rs
- xlsynth-g8r/src/get_summary_stats.rs
- xlsynth-g8r/src/lib.rs
- xlsynth-g8r/src/main.rs
- xlsynth-g8r/src/process_ir_path.rs
via a configurable-sized batch of uniform random input stimulus
> [g8r] Add flag for counting toggles

- xlsynth-driver/src/ir2gates.rs
- xlsynth-driver/src/main.rs
- xlsynth-g8r/Cargo.toml
- xlsynth-g8r/src/find_structures.rs
- xlsynth-g8r/src/fraig.rs
- xlsynth-g8r/src/main.rs
- xlsynth-g8r/src/process_ir_path.rs
When fraig sim samples is not provided we compute it as a function of the gate count.
> [g8r] Add flags for max fraig iterations and fraig sim samples

- xlsynth-estimator/src/estimator.rs
- ensure estimator specializations only match when the op matches
- add regression test for the `find_estimator_for_op` helper with explanation comment
> Fix estimator op-specific specialization

- xlsynth-g8r/src/ir_equiv_boolector.rs
- avoid zero-width shift amount when translating shifts to Boolector
- add unit tests covering 1-bit shift logic
> Fix 1‑bit shift translation for Boolector

- xlsynth-g8r/src/ir_equiv_boolector.rs
- add missing handling of `ZeroExt` nodes in the Boolector translator
- test ZeroExt operation
> Fix ZeroExt support in Boolector conversion

- xlsynth-g8r/src/ir_equiv_boolector.rs
- handle remaining `NodePayload` variants in `ir_fn_to_boolector`
- drop the wildcard branch for unhandled node translation
> [g8r] Complete Boolector translation cases

- xlsynth/src/ir_builder.rs
- reduce repetitive code in `FnBuilder` by generating simple operations with macros
- `cargo test --workspace`
> [xlsynth] Refactor FnBuilder operations

- xlsynth-g8r/Cargo.toml
- xlsynth-g8r/benches/mcmc_benchmark.rs
- xlsynth-g8r/src/bin/mcmc-driver.rs
- xlsynth-g8r/src/gate_sim.rs
- xlsynth-g8r/src/get_summary_stats.rs
- xlsynth-g8r/src/lib.rs
- xlsynth-g8r/src/mcmc_logic.rs
- xlsynth-g8r/src/netlist/parse.rs
- xlsynth-g8r/src/transforms/double_negate.rs
- xlsynth-g8r/src/transforms/duplicate.rs
- xlsynth-g8r/src/transforms/mod.rs
- xlsynth-g8r/src/transforms/redundant_and.rs
- xlsynth-g8r/src/transforms/rotate_and.rs
- xlsynth-g8r/src/transforms/swap_operands.rs
- xlsynth-g8r/src/transforms/toggle_output.rs
- xlsynth-g8r/src/transforms/transform_trait.rs
- xlsynth-g8r/src/transforms/true_and.rs
This also speeds up gatesim by getting debug formatting out of the critical path via lambda.
> [g8r] first cut of mcmc driver

- xlsynth-g8r/src/transforms/mod.rs
- xlsynth-g8r/src/transforms/toggle_operand_negation.rs
- xlsynth-g8r/src/transforms/transform_trait.rs
- add ToggleOperandNegationTransform and primitive
- register new transform in mod.rs and TransformKind
- provide unit tests for primitive and transform
> Add ToggleOperandNegation transform

- xlsynth-g8r/src/transforms/mod.rs
- xlsynth-g8r/src/transforms/push_negation.rs
- xlsynth-g8r/src/transforms/transform_trait.rs
- implement `push_negation` transform
- register the new transform
- expose it through `TransformKind`
> [g8r] Implement push_negation transform

- xlsynth-g8r/src/mcmc_logic.rs
- xlsynth-g8r/src/transforms/merge_equiv_leaves.rs
- xlsynth-g8r/src/transforms/mod.rs
- xlsynth-g8r/src/transforms/rewire_operand.rs
- xlsynth-g8r/src/transforms/swap_outputs.rs
- xlsynth-g8r/src/transforms/transform_trait.rs
- implement new reversible transform `merge_equiv_leaves`
- wire transform into transform system
- extend transform enum
- run `pre-commit`
> Add merge_equiv_leaves transform

- xlsynth-g8r/src/mcmc_logic.rs
- xlsynth-g8r/src/test_utils.rs
- xlsynth-g8r/src/transforms/factor_shared_and.rs
- xlsynth-g8r/src/transforms/mod.rs
- xlsynth-g8r/src/transforms/redundant_and.rs
- xlsynth-g8r/src/transforms/transform_trait.rs
- add `FactorSharedAnd`/`UnfactorSharedAnd` transforms
- register the transforms
- extend `TransformKind`
> [g8r] Add FactorSharedAnd transform, adjust transform weights

- run_valgrind_on_tests.py
- xlsynth-sys/build.rs
- xlsynth-sys/src/lib.rs
- xlsynth/src/vast.rs
- xlsynth/tests/vast_test.rs
Uses new APIs from DSO release v0.0.196
> [vast] Add support for flop oriented sequential constructs.

- xlsynth-g8r/src/xls_ir/ir_parser.rs
This isn't quite right/complete because we still have some spots we look for composite strings like ", pos=" but that's existing tech debt, this helps with at least things like easy/clear end of construct comments.
> [g8r:ir_parse] First cut dropping EOL delimited comments.

- xlsynth-g8r/src/equiv/easy_smt_backend.rs
- xlsynth-g8r/src/equiv/mod.rs
- xlsynth-g8r/src/equiv/prove_equiv.rs
- xlsynth-g8r/src/equiv/solver_interface.rs
commit-id:1a68f086
---
**Stack**:
- #426
- #420
- #419
- #415
- #413
- #412
- #411
- #410
- #409 ⬅
- #408
- #407
- #406
- #405
- #404
> Add nary operators

- xlsynth-g8r/Cargo.toml
- xlsynth-g8r/src/equiv/bitwuzla_backend.rs
- xlsynth-g8r/src/equiv/easy_smt_backend.rs
- xlsynth-g8r/src/equiv/mod.rs
- xlsynth-g8r/src/equiv/prove_equiv.rs
- xlsynth-g8r/src/equiv/solver_interface.rs
commit-id:afdfc934
---
**Stack**:
- #426
- #420
- #419
- #415
- #413 ⬅
> Add term cache for easy SMT

- xlsynth-g8r/src/equiv/prove_equiv.rs
- xlsynth-g8r/src/equiv/solver_interface.rs
commit-id:c111a684
---
**Stack**:
- #426
- #420
- #419
- #415
- #413
- #412
- #411 ⬅
- #410
> Add selection operations

- xlsynth-g8r/Cargo.toml
- xlsynth-g8r/src/equiv/boolector_backend.rs
- xlsynth-g8r/src/equiv/mod.rs
**Stack**:
- #426
- #420
- #419
- #415 ⬅
- #413
- #412
- #411
- #410
> Add boolector static backend

- xlsynth-g8r/Cargo.toml
- xlsynth-g8r/src/equiv/boolector_backend.rs
- xlsynth-g8r/src/equiv/mod.rs
The git spr seems not robust enough across changes in its configuration and this caused some commits to be merged incorrectly and some PRs are lost (including this one). This pull request rescues the commit and add support for a boolector backend.
> Rescue commit 9473322 for boolector backend

- xlsynth-test-helpers/src/ir_fuzz.rs
The git spr seems not robust enough across changes in its configuration and this caused some commits to be merged incorrectly and some PRs are lost (including this one). This pull request rescues the commit.
Original commit message:
The fuzzer generates invalid bit_slice operations where start + width is greater than the bit-width of the operand. This pull request rules out this.
commit-id:1b3c18d7
> Fix fuzzer

- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_opt_equiv.rs
commit-id:32e80a21
---
**Stack**:
- #434
- #433 ⬅
> Fix fuzzer compile flags

- xlsynth-g8r/src/equiv/prove_equiv.rs
This pull request refactors the xlsynth-g8r/src/equiv/prove_equiv.rs file to reduce macro usage. Macros in xlsynth-g8r/src/equiv/solver_interface.rs isn't touched as such refactoring is time-consuming.
commit-id:c26e3b1f
---
**Stack**:
- #451
- #450
- #449
- #446
- #445
- #444
- #443
- #442
- #441 ⬅
> Refactor test suite to reduce macro usage

- xlsynth-g8r/src/equiv/bitwuzla_backend.rs
- xlsynth-g8r/src/equiv/boolector_backend.rs
- xlsynth-g8r/src/equiv/easy_smt_backend.rs
- xlsynth-g8r/src/equiv/prove_equiv.rs
- xlsynth-sys/src/lib.rs
- xlsynth/src/ir_value.rs
- xlsynth/src/lib_support.rs
commit-id:97419a38
---
**Stack**:
- #451
- #450
- #449
- #446
- #445
- #444
- #443
- #442 ⬅
> Add get_value for zero-sized token

- .github/workflows/ci.yml
- xlsynth-driver/src/ir_equiv.rs
- xlsynth-driver/src/main.rs
- xlsynth-g8r/fuzz/Cargo.toml
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_opt_equiv.rs
- xlsynth-g8r/src/bin/check-ir-equivalence.rs
- xlsynth-g8r/src/equiv/prove_equiv.rs
commit-id:22ae8df2
---
**Stack**:
- #454
- #451
- #450
- #449
- #446 ⬅
> Fix fuzzer flags

- xlsynth-driver/src/ir_equiv.rs
- xlsynth-driver/src/main.rs
- xlsynth-driver/tests/invoke_test.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_opt_equiv.rs
- xlsynth-g8r/src/bin/check-ir-equivalence.rs
- xlsynth-g8r/src/equiv/prove_equiv.rs
commit-id:2a9a45ce
---
**Stack**:
- #454
- #451
- #450
- #449 ⬅
> Add handling for implicit token

- xlsynth-sys/build.rs
Yet another attempt to make things work well when we're behind a MITM TLS
proxy.
> Shell out to curl if download with ureq fails.

- xlsynth-driver/src/gv_read_stats.rs
- xlsynth-g8r/src/netlist/gatefn_from_netlist.rs
- xlsynth-g8r/src/netlist/parse.rs
- xlsynth-g8r/src/netlist/stats.rs
Also support assign statements which are sometimes used for tie-offs e.g. on output signals.
> Fix gv.gz reading for stats.

- xlsynth-driver/README.md
- xlsynth-driver/src/dslx_show.rs
- xlsynth-driver/src/main.rs
- xlsynth-driver/tests/invoke_test.rs
- xlsynth-sys/src/lib.rs
- xlsynth/src/dslx.rs
This PR introduces a new command `dslx-show` to show the definition for some symbol.
> Add dslx-show

- xlsynth-g8r/src/xls_ir/ir_deduce.rs
- xlsynth-g8r/src/xls_ir/ir_verify.rs
- xlsynth-g8r/src/xls_ir/mod.rs
Helps the verify module to flag weird stuff if we ever produce it by accident.
> Start on deduce rules for IR nodes.

- xlsynth-driver/README.md
- xlsynth-driver/src/dslx_equiv.rs
- xlsynth-driver/src/lib.rs
- xlsynth-driver/src/main.rs
- xlsynth-driver/src/proofs/mod.rs
- xlsynth-driver/src/proofs/obligations.rs
- xlsynth-driver/src/proofs/plans.rs
- xlsynth-driver/src/proofs/script.rs
- xlsynth-driver/src/proofs/source.rs
- xlsynth-driver/src/proofs/tactics.rs
- xlsynth-driver/src/proofs/tactics/cosliced.rs
- xlsynth-driver/src/proofs/tactics/focus.rs
- xlsynth-driver/src/proofs/tactics/utils.rs
- xlsynth-driver/src/prover.rs
- xlsynth-driver/src/prover_config.rs
Add basic prover script support and `cosliced` and `focus` tactics.
> Add basic prover script

- xlsynth-driver/README.md
- xlsynth-driver/src/dslx_equiv.rs
- xlsynth-driver/src/ir_equiv.rs
- xlsynth-driver/src/ir_equiv_blocks.rs
- xlsynth-driver/src/ir_localized_eco.rs
- xlsynth-driver/src/main.rs
- xlsynth-driver/src/prove_quickcheck.rs
- xlsynth-driver/src/prover_config.rs
- xlsynth-driver/tests/invoke_test.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_gate_transform_arbitrary.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_opt_equiv.rs
- xlsynth-g8r/fuzz/fuzz_targets/fuzz_ir_outline_equiv.rs
- xlsynth-prover/Cargo.toml
- xlsynth-prover/src/assertion_filter.rs
- xlsynth-prover/src/lib.rs
- xlsynth-prover/src/prove_equiv.rs
- xlsynth-prover/src/prove_quickcheck.rs
- xlsynth-prover/src/prover.rs
This pull request adds an assertion filter based on the assertion labels to have finer-grained control to suppress some assertions.
> Add assertion filter

- download_release.py
Infers the output directory name based on the latest released version and gives you a list of platforms you can select from.
> Make download release a more user friendly CLI.
